export interface PlantSettings {
  englishName: string;
  arabicName: string;
  scientificName: string;
  minMoisture: number;
  maxMoisture: number;
  minTemperature: number;
  maxTemperature: number;
  minHumidity: number;
  maxHumidity: number;
  lightRequirement: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  careLevel: 'Low' | 'Medium' | 'High';
  petWarning: boolean;
  description: string;
}

export const PLANTS_DATABASE: Record<string, PlantSettings> = {
  'spider plant': {
    englishName: 'Spider Plant',
    arabicName: 'نبات العنكبوت',
    scientificName: 'Chlorophytum comosum',
    minMoisture: 40,
    maxMoisture: 60,
    minTemperature: 18,
    maxTemperature: 27,
    minHumidity: 40,
    maxHumidity: 60,
    lightRequirement: 'Bright indirect light',
    difficulty: 'Easy',
    careLevel: 'Low',
    petWarning: false,
    description: 'Beginner-friendly houseplant that tolerates some neglect and prefers lightly moist soil.',
  },
  'snake plant': {
    englishName: 'Snake Plant',
    arabicName: 'نبتة الثعبان',
    scientificName: 'Dracaena trifasciata',
    minMoisture: 20,
    maxMoisture: 40,
    minTemperature: 15,
    maxTemperature: 24,
    minHumidity: 30,
    maxHumidity: 50,
    lightRequirement: 'Indirect light to partial shade',
    difficulty: 'Easy',
    careLevel: 'Low',
    petWarning: true,
    description: 'Very resilient drought-tolerant houseplant that prefers dry soil and low humidity.',
  },
  pothos: {
    englishName: 'Pothos',
    arabicName: 'البوتس',
    scientificName: 'Epipremnum aureum',
    minMoisture: 40,
    maxMoisture: 60,
    minTemperature: 18,
    maxTemperature: 30,
    minHumidity: 40,
    maxHumidity: 60,
    lightRequirement: 'Bright indirect light',
    difficulty: 'Easy',
    careLevel: 'Low',
    petWarning: true,
    description: 'Adaptable trailing houseplant that grows well in typical home conditions and indirect light.',
  },
  'peace lily': {
    englishName: 'Peace Lily',
    arabicName: 'زنبق السلام',
    scientificName: 'Spathiphyllum',
    minMoisture: 50,
    maxMoisture: 70,
    minTemperature: 12,
    maxTemperature: 24,
    minHumidity: 40,
    maxHumidity: 60,
    lightRequirement: 'Bright indirect light',
    difficulty: 'Easy',
    careLevel: 'Medium',
    petWarning: true,
    description: 'Popular tropical houseplant that prefers regular moderate watering and indirect light.',
  },
  monstera: {
    englishName: 'Monstera',
    arabicName: 'مونستيرا',
    scientificName: 'Monstera deliciosa',
    minMoisture: 60,
    maxMoisture: 80,
    minTemperature: 18,
    maxTemperature: 30,
    minHumidity: 50,
    maxHumidity: 70,
    lightRequirement: 'Bright indirect light',
    difficulty: 'Medium',
    careLevel: 'Medium',
    petWarning: true,
    description: 'Large tropical foliage plant that prefers moist but well-drained soil and moderate to high humidity.',
  },
  'rubber plant': {
    englishName: 'Rubber Plant',
    arabicName: 'نبات المطاط',
    scientificName: 'Ficus elastica',
    minMoisture: 50,
    maxMoisture: 70,
    minTemperature: 15,
    maxTemperature: 30,
    minHumidity: 40,
    maxHumidity: 60,
    lightRequirement: 'Bright filtered light',
    difficulty: 'Easy',
    careLevel: 'Medium',
    petWarning: true,
    description: 'Glossy-leaved indoor ficus that prefers bright filtered light and moderate watering.',
  },
  'boston fern': {
    englishName: 'Boston Fern',
    arabicName: 'سرخس بوسطن',
    scientificName: 'Nephrolepis exaltata',
    minMoisture: 60,
    maxMoisture: 80,
    minTemperature: 15,
    maxTemperature: 28,
    minHumidity: 60,
    maxHumidity: 80,
    lightRequirement: 'Bright filtered light',
    difficulty: 'Medium',
    careLevel: 'High',
    petWarning: false,
    description: 'Humidity-loving fern that prefers moist soil, filtered light, and good air humidity.',
  },
  'areca palm': {
    englishName: 'Areca Palm',
    arabicName: 'نخلة الأريكا',
    scientificName: 'Dypsis lutescens',
    minMoisture: 40,
    maxMoisture: 60,
    minTemperature: 18,
    maxTemperature: 27,
    minHumidity: 60,
    maxHumidity: 80,
    lightRequirement: 'Bright indirect light',
    difficulty: 'Medium',
    careLevel: 'High',
    petWarning: false,
    description: 'Indoor palm that prefers bright indirect light, steady moisture, and higher humidity.',
  },
  'zz plant': {
    englishName: 'ZZ Plant',
    arabicName: 'نبات زي زي',
    scientificName: 'Zamioculcas zamiifolia',
    minMoisture: 20,
    maxMoisture: 40,
    minTemperature: 15,
    maxTemperature: 30,
    minHumidity: 40,
    maxHumidity: 60,
    lightRequirement: 'Indirect light to full shade',
    difficulty: 'Easy',
    careLevel: 'Low',
    petWarning: true,
    description: 'Tough low-maintenance houseplant that tolerates shade and dry soil well.',
  },
  'chinese evergreen': {
    englishName: 'Chinese Evergreen',
    arabicName: 'الأجلونيما',
    scientificName: 'Aglaonema modestum',
    minMoisture: 40,
    maxMoisture: 60,
    minTemperature: 15,
    maxTemperature: 28,
    minHumidity: 50,
    maxHumidity: 70,
    lightRequirement: 'Bright filtered light',
    difficulty: 'Easy',
    careLevel: 'Medium',
    petWarning: true,
    description: 'Adaptable foliage houseplant that prefers filtered light, moderate moisture, and some humidity.',
  },
  philodendron: {
    englishName: 'Philodendron',
    arabicName: 'فيلوديندرون',
    scientificName: 'Philodendron',
    minMoisture: 40,
    maxMoisture: 60,
    minTemperature: 18,
    maxTemperature: 27,
    minHumidity: 40,
    maxHumidity: 60,
    lightRequirement: 'Bright indirect light',
    difficulty: 'Easy',
    careLevel: 'Low',
    petWarning: true,
    description: 'Low-maintenance tropical foliage plant that prefers indirect light and moderate watering.',
  },
  dracaena: {
    englishName: 'Dracaena',
    arabicName: 'دراسينا',
    scientificName: 'Dracaena',
    minMoisture: 40,
    maxMoisture: 60,
    minTemperature: 18,
    maxTemperature: 30,
    minHumidity: 50,
    maxHumidity: 70,
    lightRequirement: 'Bright indirect light',
    difficulty: 'Easy',
    careLevel: 'Medium',
    petWarning: true,
    description: 'Popular indoor foliage plant that prefers warm rooms, indirect light, and filtered water.',
  },
  'parlor palm': {
    englishName: 'Parlor Palm',
    arabicName: 'نخلة الصالون',
    scientificName: 'Chamaedorea elegans',
    minMoisture: 40,
    maxMoisture: 60,
    minTemperature: 20,
    maxTemperature: 27,
    minHumidity: 40,
    maxHumidity: 60,
    lightRequirement: 'Bright indirect light to partial shade',
    difficulty: 'Easy',
    careLevel: 'Medium',
    petWarning: false,
    description: 'Compact indoor palm that tolerates partial shade and prefers moderate humidity.',
  },
  anthurium: {
    englishName: 'Anthurium',
    arabicName: 'أنثوريوم',
    scientificName: 'Anthurium',
    minMoisture: 50,
    maxMoisture: 70,
    minTemperature: 16,
    maxTemperature: 30,
    minHumidity: 60,
    maxHumidity: 80,
    lightRequirement: 'Bright indirect light',
    difficulty: 'Medium',
    careLevel: 'High',
    petWarning: true,
    description: 'Tropical flowering houseplant that prefers warmth, high humidity, and bright indirect light.',
  },
  peperomia: {
    englishName: 'Peperomia',
    arabicName: 'بيبيروميا',
    scientificName: 'Peperomia',
    minMoisture: 40,
    maxMoisture: 60,
    minTemperature: 18,
    maxTemperature: 30,
    minHumidity: 50,
    maxHumidity: 70,
    lightRequirement: 'Bright indirect light',
    difficulty: 'Easy',
    careLevel: 'Low',
    petWarning: false,
    description: 'Compact adaptable houseplant that dislikes overwatering and prefers partial drying between waterings.',
  },
  calathea: {
    englishName: 'Calathea',
    arabicName: 'كالاتيا',
    scientificName: 'Goeppertia / Calathea',
    minMoisture: 50,
    maxMoisture: 70,
    minTemperature: 18,
    maxTemperature: 30,
    minHumidity: 60,
    maxHumidity: 80,
    lightRequirement: 'Bright indirect light',
    difficulty: 'Medium',
    careLevel: 'High',
    petWarning: false,
    description: 'Patterned tropical foliage plant that prefers warmth, high humidity, and indirect light.',
  },
  'kentia palm': {
    englishName: 'Kentia Palm',
    arabicName: 'نخلة الكينتيا',
    scientificName: 'Howea forsteriana',
    minMoisture: 40,
    maxMoisture: 60,
    minTemperature: 16,
    maxTemperature: 27,
    minHumidity: 40,
    maxHumidity: 60,
    lightRequirement: 'Bright indirect light',
    difficulty: 'Easy',
    careLevel: 'Medium',
    petWarning: false,
    description: 'Elegant indoor palm that tolerates lower light and drier air better than many palms.',
  },
  'bird of paradise': {
    englishName: 'Bird of Paradise',
    arabicName: 'عصفور الجنة',
    scientificName: 'Strelitzia reginae',
    minMoisture: 60,
    maxMoisture: 80,
    minTemperature: 18,
    maxTemperature: 30,
    minHumidity: 60,
    maxHumidity: 80,
    lightRequirement: 'Bright light',
    difficulty: 'Medium',
    careLevel: 'High',
    petWarning: true,
    description: 'Large tropical plant that prefers bright light, regular watering, and high humidity.',
  },
  'cast iron plant': {
    englishName: 'Cast Iron Plant',
    arabicName: 'نبات الحديد الزهر',
    scientificName: 'Aspidistra',
    minMoisture: 40,
    maxMoisture: 60,
    minTemperature: 10,
    maxTemperature: 20,
    minHumidity: 40,
    maxHumidity: 60,
    lightRequirement: 'Low to filtered light',
    difficulty: 'Easy',
    careLevel: 'Low',
    petWarning: false,
    description: 'Very resilient shade-tolerant houseplant that handles tough indoor spots with little care.',
  },
  alocasia: {
    englishName: 'Alocasia',
    arabicName: 'ألوكاسيا',
    scientificName: 'Alocasia',
    minMoisture: 50,
    maxMoisture: 70,
    minTemperature: 18,
    maxTemperature: 30,
    minHumidity: 60,
    maxHumidity: 80,
    lightRequirement: 'Bright indirect light',
    difficulty: 'Hard',
    careLevel: 'High',
    petWarning: true,
    description: 'Showy tropical plant that needs warmth, high humidity, and careful watering.',
  },
};

export const PLANT_CATEGORIES = {
  Houseplants: Object.keys(PLANTS_DATABASE),
};

export function normalizePlantSearch(value: string): string {
  return value.toLowerCase().trim().replace(/\s+/g, ' ');
}

export function getPlantSettings(plantName: string): PlantSettings | undefined {
  const search = normalizePlantSearch(plantName);

  if (PLANTS_DATABASE[search]) {
    return PLANTS_DATABASE[search];
  }

  return Object.values(PLANTS_DATABASE).find((plant) => {
    return (
      normalizePlantSearch(plant.englishName) === search ||
      normalizePlantSearch(plant.arabicName) === search ||
      normalizePlantSearch(plant.scientificName) === search
    );
  });
}

export function isValidPlant(plantName: string): boolean {
  return !!getPlantSettings(plantName);
}